// Construction/Destruction:

template<class T>
rsDelay<T>::rsDelay()
{
  maxDelay  = 3;
  delayLine = new T[maxDelay+1];
  tapIn     = 0;
  tapOut    = 0;
  reset();

  // Maybe avoid this allocation of a buffer with 3 samples. It will most certainly be wasted 
  // because soon the client will request an allocation of a more sensible size. But then we must
  // deal with the possibility of having a nullptr. That's the tradeoff here: either always do 
  // wasted allocations or accept that pointer could initially be null. Or maybe a trick could be 
  // used: just let pointer initially point to some static member variable. We might apply a sort
  // of "null object" pattern to the pointer variable. But I'm not sure, if that's workable. And 
  // why 3. If anything, we should use 1. Or maybe even 0. But verify if the bit-masking will work
  // or if this is a weird edge case.

  // Maybe implement a function 
  // 
  //   bool isReady() const;
  //
  // that checks if delayLine is not nullptr (and maybe if maxDelay > 0) and if the distances 
  // between tapIn and tapOut is inside the valid range. Maybe call the function isStateValid()
  // or something. This should become a general idiom throughout the library to have such sanity
  // self-tests. These can then be checked in an assertions whereever appropriate. With such 
  // assertions in place, we could perhaps get away with not allocating in the constructor.

}

template<class T>
rsDelay<T>::~rsDelay()
{
  if( delayLine != nullptr )   // Check if we need this conditional. If not, remove it.
    delete[] delayLine;
  delayLine = nullptr;
}



// -----------------------------------------------------
// Generated by GPT-5 mini. Needs review and unit tests.

// PSEUDOCODE / PLAN:
//
// Implement copy and move semantics for template<class T> rsDelay<T>.
// Goals:
//  - Copy constructor: allocate new buffer of size other.maxDelay+1 if other.delayLine != nullptr,
//    copy elements, copy tapIn/tapOut and maxDelay.
//  - Move constructor: steal other.delayLine and metadata, set other.delayLine to nullptr and reset other state.
//  - Copy assignment: protect against self-assignment. Allocate new buffer first (strong exception safety),
//    copy elements, delete old buffer, assign new pointer and metadata.
//  - Move assignment: protect against self-assignment. Delete current buffer, steal other's pointer and metadata,
//    null out other's pointer and reset other's metadata. Mark noexcept for moves.
//  - Handle case where other.delayLine == nullptr (moved-from or otherwise) gracefully.
//  - Keep implementation consistent with existing style (use plain loops for copying).
//
// Detailed steps in each function:
//  - Copy ctor:
//      maxDelay = other.maxDelay
//      if other.delayLine:
//          delayLine = new T[maxDelay+1]
//          for i in 0..maxDelay: delayLine[i] = other.delayLine[i]
//      else delayLine = nullptr
//      tapIn = other.tapIn; tapOut = other.tapOut
//  - Move ctor:
//      maxDelay = other.maxDelay
//      delayLine = other.delayLine
//      tapIn = other.tapIn; tapOut = other.tapOut
//      other.delayLine = nullptr; other.maxDelay = 0; other.tapIn = other.tapOut = 0
//  - Copy assignment:
//      if this == &other: return *this
//      allocate newBuf (or nullptr if other.delayLine==nullptr)
//      copy elements if allocated
//      delete[] delayLine
//      delayLine = newBuf; maxDelay = other.maxDelay; tapIn = other.tapIn; tapOut = other.tapOut
//      return *this
//  - Move assignment:
//      if this == &other: return *this
//      delete[] delayLine
//      delayLine = other.delayLine; maxDelay = other.maxDelay; tapIn = other.tapIn; tapOut = other.tapOut
//      other.delayLine = nullptr; other.maxDelay = 0; other.tapIn = other.tapOut = 0
//      return *this
//
// Implementations follow:

template<class T>
rsDelay<T>::rsDelay(const rsDelay<T>& other)
{
  maxDelay = other.maxDelay;
  if(other.delayLine != nullptr)
  {
    delayLine = new T[maxDelay + 1];
    for(int i = 0; i < maxDelay + 1; ++i)
      delayLine[i] = other.delayLine[i];
  }
  else
  {
    delayLine = nullptr;
  }
  tapIn  = other.tapIn;
  tapOut = other.tapOut;
}

template<class T>
rsDelay<T>::rsDelay(rsDelay<T>&& other) noexcept
{
  // Steal resources
  maxDelay = other.maxDelay;
  delayLine = other.delayLine;
  tapIn  = other.tapIn;
  tapOut = other.tapOut;

  // Leave other in a valid empty state
  other.delayLine = nullptr;
  other.maxDelay = 0;
  other.tapIn = 0;
  other.tapOut = 0;
}

template<class T>
rsDelay<T>& rsDelay<T>::operator=(const rsDelay<T>& other)
{
  if(this == &other)
    return *this;

  T* newBuf = nullptr;
  if(other.delayLine != nullptr)
  {
    newBuf = new T[other.maxDelay + 1];
    for(int i = 0; i < other.maxDelay + 1; ++i)
      newBuf[i] = other.delayLine[i];
  }

  // Delete old buffer and replace with new
  if(delayLine != nullptr)
  {
    delete[] delayLine;
  }
  delayLine = newBuf;
  maxDelay  = other.maxDelay;
  tapIn     = other.tapIn;
  tapOut    = other.tapOut;

  return *this;
}

template<class T>
rsDelay<T>& rsDelay<T>::operator=(rsDelay<T>&& other) noexcept
{
  if(this == &other)
    return *this;

  // Free current resources
  if(delayLine != nullptr)
    delete[] delayLine;

  // Steal resources from other
  delayLine = other.delayLine;
  maxDelay  = other.maxDelay;
  tapIn     = other.tapIn;
  tapOut    = other.tapOut;

  // Reset other
  other.delayLine = nullptr;
  other.maxDelay  = 0;
  other.tapIn = 0;
  other.tapOut = 0;

  return *this;
}

// End of :Generated by GPT-5 mini....
// -----------------------------------------------------




// Setup:

template<class T>
void rsDelay<T>::setMaxDelayInSamples(int newMaxDelay)
{
  if( newMaxDelay > maxDelay )
  {
    delete[] delayLine;
    maxDelay  = rsNextPowerOfTwo(newMaxDelay + 1) - 1;
    delayLine = new T[maxDelay+1];
    rsArrayTools::fillWithZeros(delayLine, maxDelay+1);
  }

  // ToDo:
  //
  // - Document the crazy +1, -1 business that is going on here
}

template<class T>
void rsDelay<T>::setDelayInSamples(int delay)
{
  rsAssert(delay >= 0 && delay <= maxDelay, 
           "Delay out of range in rsBasicDelayLine::setDelayInSamples");

  // Sanitize input argument and adjust tapOut pointer:
  delay = rsClip(delay, 0, maxDelay);
  tapOut = tapIn - delay;
  if( tapOut < 0 )
    tapOut += maxDelay+1;
}

// Misc:

template<class T>
void rsDelay<T>::reset()
{
  for(int i = 0; i < maxDelay+1; i++)
    delayLine[i] = 0.0;
}


//-------------------------------------------------------------------------------------------------

// construction/destruction:

template<class TSig, class TPar>
rsDelayTempoSynced<TSig, TPar>::rsDelayTempoSynced(int maximumDelayInSamples)
{
  length      = maximumDelayInSamples + 1;
  delayBuffer = new TSig[length+interpolatorMargin];

  tapIn      = 0;
  tapOut     = 0;
  delayTime  = TPar(0.25);
  sampleRate = TPar(44100.0);
  bpm        = TPar(120.0);
  tempoSync  = false;

  interpolator.setInterpolationMethod(rsInterpolator<TSig>::WARPED_ALLPASS);

  interpolator.setInterpolationMethod(rsInterpolator<TSig>::LINEAR);  // for debug

  setDelayTime(delayTime);
  clearDelayBuffer();
}

template<class TSig, class TPar>
rsDelayTempoSynced<TSig, TPar>::~rsDelayTempoSynced()
{
  if( delayBuffer != nullptr )
  {
    delete[] delayBuffer;
    delayBuffer = nullptr;
  }
}

// parameter settings (set-functions):

template<class TSig, class TPar>
void rsDelayTempoSynced<TSig, TPar>::setSampleRate(TPar newSampleRate)
{
  if(newSampleRate > 0.01)
  {
    sampleRate = newSampleRate;
    setupDelayInSamples();
  }
}

template<class TSig, class TPar>
void rsDelayTempoSynced<TSig, TPar>::setDelayTime(TPar newDelayTime)
{
  //delayTime = rsClip(newDelayTime, 0.0, 4.25);
  delayTime = newDelayTime;
  setupDelayInSamples();
}

template<class TSig, class TPar>
void rsDelayTempoSynced<TSig, TPar>::setSyncMode(bool shouldTempoSync)
{
  tempoSync = shouldTempoSync;
  setupDelayInSamples();
}

template<class TSig, class TPar>
void rsDelayTempoSynced<TSig, TPar>::setTempoInBPM(TPar newTempoInBPM)
{
  if(newTempoInBPM >= 0.0)
  {
    bpm = newTempoInBPM;
    setupDelayInSamples();
  }
  else
    rsError("Tempo < 0");
}

template<class TSig, class TPar>
void rsDelayTempoSynced<TSig, TPar>::setInterpolationMethod(int newMethod)
{
  if(newMethod <= rsInterpolator<TSig>::WARPED_ALLPASS)
    interpolator.setInterpolationMethod(newMethod);
  else
    rsError("Unknown interpolation method");
}

// others:

template<class TSig, class TPar>
void rsDelayTempoSynced<TSig, TPar>::clearDelayBuffer()
{
  for(int i=0; i<length+interpolatorMargin; i++)
    delayBuffer[i] = 0.0;
  interpolator.reset();
}

template<class TSig, class TPar>
void rsDelayTempoSynced<TSig, TPar>::setupDelayInSamples()
{
  double delayInSeconds;
  if( tempoSync )
    delayInSeconds = rsBeatsToSeconds(delayTime, bpm);
  else
    delayInSeconds = delayTime;
    // get rid of the temposync stuff

  delayInSamples = sampleRate*delayInSeconds;
  delayInSamples = rsClip(delayInSamples, (TPar)(interpolatorMargin-1),
    (TPar) (length-1-interpolatorMargin));
  //delayInSamples = clip(delayInSamples, (double)(interpolatorMargin-1),
  //  (double) (length-1-interpolatorMargin)); // old


  // update member delayTime to the clipped value:
  delayInSeconds = delayInSamples / sampleRate;
  if( tempoSync )
    delayTime = rsSecondsToBeats(delayInSeconds, bpm);
  else
    delayTime = delayInSeconds;

  // calculate the integer and fractional parts of the delay:
  TPar tmp   = floor(delayInSamples);
  int  dInt  = (int) tmp;
  TPar dFrac = delayInSamples - tmp;
  frac         = 1.0 - dFrac; // because we look backwards

                              // adjust tapOut-pointer:
  tapOut = tapIn - dInt - 1;
  if( frac >= 1.0 )
  {
    frac    = 0.0;
    tapOut += 1;
  }
  tapOut = wrapAround(tapOut);
}


//=================================================================================================
/*


ToDo:

- Refactor the code in such a way that delayline classes never know about sample-rates and delay
  times in seconds. They should just know about the delay in samples. This kind of information 
  should really be held at a higher level.

- Maybe bring back the delayline implementation that is set up in terms of a time (in seconds) 
  and a sample rate and call it rsDelayTimeBased. It's in Misc\UnusedCode\Misc.h

- Use only one pointer for tapIn and tapOut (see Julius Smith's PASP-book)

- Maybe add functions getMaxDelayLineLength() (or just getMaxLength() or getMaxLengthInSamples()) 
  which should return maxDelay+1. Same for the actual delay. The +1 is a trivial transformation but
  the point of having these functions lies in their documentation value rather than in doing useful
  work. Their existence communicates to the user that the delay and delay line length are not the 
  same (they differ by 1). That may help to avoid off-by-one bugs in client code. I know because I 
  had such a bug in rsPlotDelayLineContent().

*/