
template<class T> 
void rsPitchDitherProto<T>::fillSawCycle(T* x, int N, T amp)
{
  T s = T(2) / T(N-1);
  for(int n = 0; n < N; n++)
    x[n] = amp * (-1 + s * T(n));

  // ToDo:
  //
  // - Maybe have an optional "anti-alias" parameter (defaulting to false). If it's true, create 
  //   the saw additively or maybe by means of an iFFT. Maybe have two functions fillSawNaive(), 
  //   fillSawAntiAliased() and use this function here as dispatcher.
}

template<class T> 
void rsPitchDitherProto<T>::fillSawCycle(
  std::vector<T>& x, int* start, int length, T amp, int* counter)
{  
  fillSawCycle(&x[*start], length, amp); 
  *start += length;
  if(counter != nullptr)
    (*counter)++;
}

template<class T> 
void rsPitchDitherProto<T>::fillDitherSawMinVariance(
  std::vector<T>& x, T period, unsigned long seed, T amp)
{
  rsNoiseGenerator<T> prng;
  prng.setRange(0.0, 1.0);             // Q: Is the interval open, closed or half-open?
  prng.setSeed(seed);

  int N  = (int) x.size();
  int L1 = rsFloorInt(period);
  int L2 = L1 + 1;
  T   f  = period - L1;
  int n  = 0;                          // Sample number
  while(true)
  {
    if(n >= N - L2)                    // Verify! Maybe we need to subtract 1 from the RHS?
      break;
    T r = prng.getSample();            // Random number in [0..1) ..or is it [0..1]?
    r = T(1) - r;                      // To make the output match getSaw(). See Notes.
    if(r <= f)
      fillSawCycle(x, &n, L2, amp);    // Probability for that branch is f
    else
      fillSawCycle(x, &n, L1, amp);    // Probability for that branch is 1-f
  }

  // Notes:
  //
  // - We need to use the complementary random value 1-r here to match the output of getSaw() using 
  //   distributionMinVariance(). I think, it may behave differently in edge cases (whose 
  //   probability should be zero with infinite precision numbers and very low with floats), 
  //   though. The complementation should change the random range from the interval [0,1) to (0,1].
  //   Maybe we could fix it by using <= instead of < or vice versa. This would switch the behavior
  //   in the highly unlikely edge case. I think, using <= may actually be consistent with what we
  //   want because in getSaw() we use < and don't use the complementary value. ToDo: Cook up a 
  //   unit test that actually hits the edge case. Maybe try to use a seed that ensures that the 
  //   next produced integer value in the prng is the 2^32 - 1. That's the maximum value of the 
  //   whole range integer range and should map to a floating point value barely below 1. We could 
  //   find the required seed by using a "downdateState()" function in the prng. Such a function 
  //   does not yet exist but there are some comments in rsNoiseGenerator about how this could be 
  //   implemented.
  //
  //
  // Maybe it should use if(r < f) rather than if(r <= f) because then it would also work correctly
  // when r = 0. In that case, we should always use L1, i.e. always use the else-branch. With a
  // conditional if(f < 0) this would be the case because r < 0 is impossible. With <= 0, it would
  // still be possible to execute the if-branch, although the probability is theoretically zero if 
  // r and f were real numbers with infinite precision rather than floating point numbers. So maybe
  // it doesn't matter much but for the sake of theoretical correctness. Or wait - is that actually 
  // correct? Or should we always use the if-branch in the r = 0 case? Figure that out and document
  // it! Figure out if the prng produces values in the closed, half-open or open interval 0..1 and 
  // in half-open case, which side is open. I think, it is probably left-closed and right-open, 
  // i.e. [0..1) because when looking at underlying integer modular arithmetic, we produce values
  // in the range 0...2^32-1, I think. So, the modulus 2^32 is never produced.
  // OK - done. We use if(r < f) now. I think, that's the correct way to do it.
}

template<class T> 
std::vector<T> rsPitchDitherProto<T>::getSawCycle(int N, T amp)
{  
  std::vector<T> cycle(N);
  fillSawCycle(&cycle[0], N, amp);
  return cycle;

}

/** Writes the content of the source vector "src" into the destination vector "dst" starting at 
index "n" inside "dst". If the "src" vector is longer than the part of "dst" that starts as "n", 
then the content of "src" with only be written partially into "dst" just to fill it up to its 
end. */
template<class T>
void rsWriteContentAtOld(const std::vector<T>& src, std::vector<T>& dst, size_t n)
{
  size_t Nsrc = src.size();
  size_t Ndst = dst.size();
  for(size_t i = 0; i < Nsrc; i++)
  {
    if(n + i >= Ndst)
      break;
    dst[n + i] = src[i];
  }
  // ToDo: Verify code. It was generated by Copilot. If all is well, maybe move into RAPT library.
  // Maybe return the number of items written. That requires changing the for-loop to a while-loop
  // such that the loop counter i remains avialbale after exiting the loop. That might even be more 
  // efficient anyway because then we would only check one condition in each loop iteration.
}

template<class T> 
std::vector<T> rsPitchDitherProto<T>::getSawOld(
  int N, const CycleDistribution& cd, unsigned long seed, T amp)
{
  // Sanity checks:
  rsAssert(N >= 0);
  T P = cd.p1*cd.L1 + cd.p2*cd.L2 + cd.p3*cd.L3;  // Reconstruct desired period.
  rsAssert(isCycleDistributionValid(P, cd)); 

  using Vec = std::vector<T>;

  // Create 3 saw cycles of the 3 lengths that may be used:
  Vec cycleL1 = getSawCycle(cd.L1, amp);
  Vec cycleL2 = getSawCycle(cd.L2, amp);
  Vec cycleL3 = getSawCycle(cd.L3, amp);

  // Set up the pseudo random number generator:
  rsNoiseGenerator<T> prng;
  prng.setRange(0.0, 1.0);             // Q: Is the interval open, closed or half-open?
  prng.setSeed(seed);

  // Create the sawtooth wave signal using one of the 3 prototype cycles for each cycle of the saw:
  Vec saw(N);
  size_t n = 0;
  while(n < (size_t) N)
  {
    T r = prng.getSample();
    if(r < cd.p1)
    {
      rsWriteContentAtOld(cycleL1, saw, n);
      n += cd.L1;
    }
    else if(r >= cd.p1 + cd.p2)
    {
      rsWriteContentAtOld(cycleL3, saw, n);
      n += cd.L3;
    }
    else
    {
      rsWriteContentAtOld(cycleL2, saw, n);
      n += cd.L2;
    }
  }

  return saw;

  // ToDo: 
  // 
  // - Verify if usage of < vs <= and > vs >= is correct when checking r against cd.p1 etc.. I 
  //   think that can be decided only when we made a decision whether p1 or p3 should be zero in 
  //   the edge case of an integer desired period P. Perhaps it makes more sense to set p1 to zero
  //   in the case if we want to maintain that the middle length L2 is always floor(P) which seems
  //   to be a sensible convention. Of course, it would be best, if it would work correctly if any
  //   of p1,p2,p3 is zero. If that's not possible, the priority list is: p1,p3,p2
  // 
  // - I think, it is indeed correct. We could rewrite it in such a way that the 2nd branch 
  //   produces the cycles of length L2 and the 3rd branch those of length L3. To achieve this, we
  //   would have to change the "else-if" condition to "else if(r < cd.p1 + cd.p2)". Doing it like 
  //   that may look more orderly and could straightforwardly be generalized to more lengths and 
  //   probabilities. In such a more general scenario, each branch would compare  r  using  <  
  //   against the accumulated probability value p1 + p2 + p3 + .... We would sum up to pN and 
  //   produce a cycle of length LN.
  //
  // - Maybe let rsWriteContentAt() return the number of items written and then use:
  //   n += rsWriteContentAt(..) to compactify the 3 branches into 1-liners.
  //
  // - The function has been renamed to getSawOld() with the intention to provide a new getSaw()
  //   implementation doing what is suggested in the two points above. ..ok - done. Now we sould 
  //   implement a unit test that ensures that the old and new version produce the same results. 
  //   If it all works well, maybe the old version can eventually be deleted.
}

/** Writes the content of the source vector "src" into the destination vector "dst" starting at 
index "n" inside "dst". If the "src" vector is longer than the part of "dst" that starts as "n", 
then the content of "src" with only be written partially into "dst" just to fill it up to its 
end. The return value is the number of items written. */
template<class T>
size_t rsWriteContentAt(const std::vector<T>& src, std::vector<T>& dst, size_t n)
{
  size_t Ns = src.size();
  size_t Nd = dst.size();
  size_t i  = 0;
  while(i < Ns && n+i < Nd)
  {
    dst[n+i] = src[i];
    i++;
  }
  return i;

  // ToDo: Verify code by inspection and write unit tests. Maybe we could use memcpy() to optimize
  // this? But then it would only work for types T that are trivially copyable. Maybe we could have
  // two versions rsWriteContentAtViaMemcpy(), rsWriteContentAtViaAssign() and then do a compile
  // time dispatch here based on the type T.
}

template<class T> 
std::vector<T> rsPitchDitherProto<T>::getSaw(
  int N, const CycleDistribution& cd, unsigned long seed, T amp)
{
  // Sanity checks:
  rsAssert(N >= 0);
  T P = cd.p1*cd.L1 + cd.p2*cd.L2 + cd.p3*cd.L3;  // Reconstruct desired period P for..
  rsAssert(isCycleDistributionValid(P, cd));      // ..this test here. It's not needed elswehere.

  // Create 3 saw cycles of the 3 lengths that may be used:
  using Vec = std::vector<T>;
  Vec cycleL1 = getSawCycle(cd.L1, amp);
  Vec cycleL2 = getSawCycle(cd.L2, amp);
  Vec cycleL3 = getSawCycle(cd.L3, amp);

  // Set up the pseudo random number generator:
  //rsNoiseGenerator<T> prng;
  //prng.setRange(0.0, 1.0);                        // The interval is half open: [0,1). (Verify!)
  //prng.setSeed(seed);
  rsRandomGenerator<T> prng;
  prng.setState(seed);

  // Create the sawtooth wave signal using one of the 3 prototype cycles for each cycle of the saw:
  Vec saw(N);
  size_t n = 0;
  while(n < (size_t) N)
  {
    //T r = prng.getSample();                       // Random number in interval [0,1)
    T r = prng.getSampleInUnitRange();              // Random number in interval [0,1)
    if(r < cd.p1)
      n += rsWriteContentAt(cycleL1, saw, n);
    else if(r < cd.p1 + cd.p2)
      n += rsWriteContentAt(cycleL2, saw, n);
    else
      n += rsWriteContentAt(cycleL3, saw, n);
  }
  return saw;
}

/*
template<class T> 
void rsPitchDitherProto<T>::fillDitherSaw(
  std::vector<T>& x, T period, unsigned long seed, T amp)
{
  // ToDo: Implement the deterministic dither algorithm, rename to fillDitherSawMinError
}
*/

template<class T> 
void rsPitchDitherProto<T>::distributionMinVariance(
  T period, rsPitchDitherProto<T>::CycleDistribution* cd)
{
  T periodFloor = rsFloor(period);
  T periodFrac  = period - periodFloor;

  cd->L2 = (int)periodFloor;
  cd->L3 = cd->L2 + 1;
  cd->L1 = cd->L2 - 1;                     // This length L1 will never be used because..
  cd->p1 = T(0);                           // ..the corresponding probability p1 is zero.
  cd->p2 = T(1) - periodFrac;
  cd->p3 = periodFrac;

  // Notes:
  //
  // - The distribution that minimizes the variance while still satisfying the constraint that the
  //   mean cycle length is given by "period" will use only the two lengths L2 = floor(period) and 
  //   L3 = L2 + 1. The length L1 = L2 - 1 will never actullay be used because its probability is 
  //   exactly zero. For cleanliness we assign it to a value anyway and for that we use the value 
  //   L1 = L2 - 1 to make it consistent with the other distributions.
  //
  //
  // ToDo:
  //
  // - Write unit test that verifies that using getSaw() with the distribution produced by this 
  //   function generates the same signal as using fillDitherSawMinVariance(). Maybe make sure that
  //   even when the underlying integer prng produces a values of modulus-1, we still produce L2. 
  //   That may be a bit questionable with T = float because due to rounding errors, the random 
  //   number in 0..1 after conversion from int to float may be actually be 1 rather than 1-tiny. I
  //   think, to make it work correctly, we really need to be sure that the range of the prng is 
  //   the half open interval [0,1) rather tan the closed interval [0,1]. I think, for T = double,
  //   that should be the case (but it should be verified anyway!) but for T = float, I'm not so 
  //   sure. That means, with T = float, it could occasionally happen that when the period is an 
  //   exact integer, we nevertheless occasionally produce a cycle that is one sample longer. That 
  //   should happen only in the very rare case when the random number produced by the prng is 
  //   extremely close to 1 and rounded up to exactly 1 because the decision logic in getSaw() uses
  //   < rather than <= for entering the 2nd branch. I think, we can test the the behavior in this
  //   edge case by setting the state of the prng manually to modulus-1 = 2^32 - 1. Maybe we can 
  //   use this value as seed.
}

template<class T> 
void rsPitchDitherProto<T>::distributionViaOverlap(
  T period, rsPitchDitherProto<T>::CycleDistribution* cd)
{
  T periodFloor = rsFloor(period);
  T periodFrac  = period - periodFloor;
  if(periodFrac < T(0.5))
  {
    cd->L1 = (int)periodFloor - 1;
    cd->p1 = T(0.5) * (T(0.5) - periodFrac);
    cd->p3 = T(0.5) - cd->p1;
  }
  else
  {
    cd->L1 = (int)periodFloor;                // No -1 here
    cd->p3 = T(0.5) * (periodFrac - T(0.5));
    cd->p1 = T(0.5) - cd->p3;
  }
  cd->p2 = T(0.5);                            // p2 is always 0.5
  cd->L2 = cd->L1 + 1;
  cd->L3 = cd->L2 + 1;
}

template<class T> 
void rsPitchDitherProto<T>::distributionEqualDeviation(
  T period, rsPitchDitherProto<T>::CycleDistribution* cd)
{
  T periodFloor = rsFloor(period);  
  T periodFrac  = period - periodFloor;

  // Compute lengths:
  if(periodFrac < T(0.5))
    cd->L1 = (int)periodFloor - 1;
  else
    cd->L1 = (int)periodFloor;
  cd->L2 = cd->L1 + 1;
  cd->L3 = cd->L2 + 1;

  // Compute intermediates:
  T e1 = cd->L1 - period;
  T e2 = cd->L2 - period;
  T e3 = cd->L3 - period;
  T m1 = rsAbs(e1);
  T m2 = rsAbs(e2);
  T m3 = rsAbs(e3);
  T M  = T(0.5);
  T M1 = M - m1;
  T M2 = M - m2; 
  T M3 = M - m3;
  T S  = 1 / (e3*(m1-m2) - e2*(m1-m3) + e1*(m2-m3));
  
  // Compute probabilities:
  cd->p1 = (M2*e3 - M3*e2) * S;
  cd->p2 = (M3*e1 - M1*e3) * S;
  cd->p3 = (M1*e2 - M2*e1) * S;
}

template<class T> 
void rsPitchDitherProto<T>::distributionEqualVariance(
  T period, rsPitchDitherProto<T>::CycleDistribution* cd)
{
  T periodFloor = rsFloor(period);  
  T periodFrac  = period - periodFloor;

  // Compute lengths:
  if(periodFrac < T(0.5))
    cd->L1 = (int)periodFloor - 1;
  else
    cd->L1 = (int)periodFloor;
  cd->L2 = cd->L1 + 1;
  cd->L3 = cd->L2 + 1;

  // Compute intermediates:
  T e1 = cd->L1 - period;
  T e2 = cd->L2 - period;
  T e3 = cd->L3 - period;
  T m1 = e1*e1;
  T m2 = e2*e2;
  T m3 = e3*e3;
  T M  = T(0.25);
  T M1 = M - m1;
  T M2 = M - m2; 
  T M3 = M - m3;
  T S  = 1 / (e3*(m1-m2) - e2*(m1-m3) + e1*(m2-m3));
  
  // Compute probabilities:
  cd->p1 = (M2*e3 - M3*e2) * S;
  cd->p2 = (M3*e1 - M1*e3) * S;
  cd->p3 = (M1*e2 - M2*e1) * S;

  // There is a lot of code duplication going on here! Try to refactor to get rid of it! Before
  // refactoring, establish a unit test that checks the results for periods 100.0, 100.1, 100.2,
  // 100.3,...,100.9. The only difference is the function to compute m1..m3 from e1..e3 and the
  // target value M for the weighted average of m1..m3. Maybe we could factor out a function 
  // distributionEqualMeasure(T period, CycleDistribution* cd, Func f, T mAvg). 
}

template<class T>
bool rsPitchDitherProto<T>::isCycleDistributionValid(
  T period, const rsPitchDitherProto<T>::CycleDistribution& cd)
{
  bool ok = true;
  T tol = 1024 * std::numeric_limits<T>::epsilon();
  T probSum = cd.p1 + cd.p2 + cd.p3;
  T lenMean = cd.p1*cd.L1 + cd.p2*cd.L2 + cd.p3*cd.L3;
  ok &= rsIsCloseTo(probSum, T(1),   tol);              // Probabilities must sum to 1.
  ok &= rsIsCloseTo(lenMean, period, tol);              // Lengths must average to period.
  return ok;

  // ToDo: Maybe verify that L1 >= 2 and L2 == L1 + 1, L3 = L2 + 1
}

template<class T>
typename rsPitchDitherProto<T>::CycleErrorMeasures rsPitchDitherProto<T>::getErrorMeasures(
  T period, int L1, T p1, int L2, T p2, int L3, T p3)
{
  //typename CycleErrorMeasures r;                             // Result
  CycleErrorMeasures r;                                      // Result
  r.e1  = T(L1) - period;                                    // Error for cycle of length L1
  r.e2  = T(L2) - period;                                    // Error for cycle of length L2
  r.e3  = T(L3) - period;                                    // Error for cycle of length L3
  r.mae = p1*rsAbs(r.e1) + p2*rsAbs(r.e2) + p3*rsAbs(r.e3);  // Mean absolute error
  r.var = p1*r.e1*r.e1   + p2*r.e2*r.e2   + p3*r.e3*r.e3;    // Error variance
  return r;

  // It doesn't compile without the ugly "typename" nonsense. From Copilot:
  //
  // "...typename is required whenever you refer to a nested type that depends on a template 
  // parameter. You can’t completely avoid that requirement unless you put the definition inside 
  // the class body."
}

// ToDo:
//
// - Maybe implement the production of different waveforms. A sine could be produced from a saw
//   by simply taking sin(pi*saw(t)). Let's also produce square- and triangle waves.
//
// - See: https://en.wikipedia.org/wiki/Inverse_transform_sampling  I think, we are doing a very
//   simple (and discretized) case of that general idea here. If that's indeed the case, maybe 
//   mention it (very briefly) in the documentation.